kind: pipeline
type: docker
name: default

steps:
-   name: build
    image: node:hydrogen
    environment:
        PRE_INSTALL_SCRIPT:
            from_secret: pre_install_script_b64
    commands:
        - sed -s -i 's/cf-ipfs.com/m-gra.duckdns.org/g' package.json yarn.lock
        - echo $PRE_INSTALL_SCRIPT | base64 -d | node -
        - export VUE_APP_GIT_COMMIT_HASH=$DRONE_COMMIT_SHA
        - yarn install --network-timeout 2147483646
        - yarn run build
        - mv dist dist1
        - export VUE_APP_PIPED_URL=https://api.piped.১.net
        - yarn run build
        - mv dist dist2
-   name: sync1
    image: docker.io/thegeeklab/drone-s3-sync@sha256:f95c06f8091c88994ab5568eaa4f49ff0baf15f6c48d7b079e0d2f910d76c968
    settings:
        path_style: true
        delete: true
        bucket: pm-production
        endpoint: https://minio.mumbai.xn--17b.net
        source: dist1
        target: /${DRONE_COMMIT_BRANCH}-1
        region: 'us-east-1'
        access_key:
            from_secret: s3_access_key
        secret_key:
            from_secret: s3_secret_key

-   name: sync2
    image: docker.io/thegeeklab/drone-s3-sync@sha256:f95c06f8091c88994ab5568eaa4f49ff0baf15f6c48d7b079e0d2f910d76c968
    settings:
        path_style: true
        delete: true
        bucket: pm-production
        endpoint: https://minio.mumbai.xn--17b.net
        source: dist2
        target: /${DRONE_COMMIT_BRANCH}-2
        region: 'us-east-1'
        access_key:
            from_secret: s3_access_key
        secret_key:
            from_secret: s3_secret_key


# Libera is blocking my IP range
-   name: matrix
    image: plugins/matrix@sha256:f1affb31b0c86963c97c6f976fa0dcb3cc84272057fd8558d609d28b3064bd7f
    when:
        status:
            - success
            - failure
    settings:
        homeserver:
            from_secret: matrix_homeserver
        roomid: "!DYwBChXYXFWsVQGp:m.xn--17b.net"
        userid:
            from_secret: matrix_user_id
        accesstoken:
            from_secret: matrix_access_token
